### ISSUE TITLE
Options for milestone 1

### ISSUE THREAD

**Issue by massimocode** [SMH110/Pizza-website#109]
- [x] BBQ base
This can be applied to all pizzas (except the BBQ pizza which already has it) in the add pizza modal. It costs an extra £2 (regardless of the pizza size). There should be a validation to ensure it is not added twice.

- [x] Bottles and cans options
Bottles and cans of drink have several options. This is already implemented using the price/version functionality.

- [x] Dips options
Dips (a side) have several options. This is already implemented using the price/version functionality.

- [x] Potato skins toppings 
Potato skins (a side) allows **at least** one topping of your choice. This will be implemented using the same pattern as toppings. £0.90 per additional topping, and the first topping is free. There should be validation to ensure at least 1 topping is selected, and that all toppings are valid toppings.

- [x] Free choice pizza
This will require an small exception to the toppings implementation.

- [x] Salad dressings
The salad dressings should be available on all salads, with an additional option "Both dressings". All descriptions should mention "dressing of your choice".

- [x] Haagen-Dazs
Haagen-Dazs has different flavours. This should be a new section with each option having its own item.
