### ISSUE TITLE
Options for milestone 2

### ISSUE THREAD

**Issue by massimocode** [SMH110/Pizza-website#133]
- [ ] Replacing existing toppings
Users should be able to remove or swap existing toppings on their chosen pizza.

- [ ] Half/half pizza
Users should be able to select a "half-half" pizza which allows them to choose 2 base pizzas to make up their half-half pizza. An additional £3 is charged on top of the price of the most expensive base chosen.

- [ ] Half/half pizza with additional toppings
Users should be able to add additional toppings to the base pizza chosen in each half of their pizza. TODO: Confirm functionality is desirable and price of toppings per-half.

- [ ] Half/half pizza with replacing existing toppings
Users should be able to remove or swap existing toppings of the base pizza chosen in each half of their pizza. TODO: confirm functionality is desirable.
